### ISSUE TITLE
[FEAT] Config tailwind to use the new fonts

### ISSUE THREAD

**Issue by gptkrsh** [web3community/devprotocol.xyz#34]
### Detailed description

Use the fonts declared in the design

### Context

-

### Possible implementation

Add this to the stylesheet:

```css
@font-face {
                font-family: 'Whyte';
                src: url('https://devstaticasset.azureedge.net/font/ABCWhyte-Regular.woff2')
                    format('woff2');
                font-style: normal;
                font-weight: 400;
                font-display: swap;
            }

            @font-face {
                font-family: 'WhyteInktrap';
                src: url('https://devstaticasset.azureedge.net/font/ABCWhyteInktrap-Bold.woff2')
                    format('woff2');
                font-style: bold;
                font-weight: 900;
                font-display: swap;
            }

            @font-face {
                font-family: 'WhyteInktrap';
                src: url('https://devstaticasset.azureedge.net/font/ABCWhyteInktrap-Regular.woff2')
                    format('woff2');
                font-style: normal;
                font-weight: 400;
                font-display: swap;
            }
```

Then config tailwind for this: https://tailwindcss.com/docs/font-family#font-families

Also update the class names if needed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
